###
### Bolt Forms
###

## Debugging
#
# Global debugging on/off switch
#
# If enabled, ALL forms will go into debug mode.  However, when disabled an individual
# form can still enable it's own debug — specific for and to that form
debug:
    enabled: false
    address: james_top986@hotmail.com

## CSRF protection
#
# Enable CSRF protection for forms. You should leave this set to 'true', unless
# you know what you're doing.
csrf: true

# Global templates used for rendering forms and emails.
#
# You can find assorted templates to copy and modify in the templates/
# directory. Simply copy them to a directory of your choosing in your theme
# and set the template you want to override.
#
# More information on available template overrides can be found in the
# Templates section of docs.
#
# NOTE: All paths are relative of your running theme.
#
# e.g. You created your templates in the `extensions/boltforms/` directory
# inside your theme, you would use similar to:
#
#templates:
#    form: extensions/boltforms/form.twig
#    email: extensions/boltforms/email.twig
#    subject: extensions/boltforms/subject.twig
#    files: extensions/boltforms/file_browser.twig

## reCAPTCHa set up
#
# Note:
# You can get your keys from https://www.google.com/recaptcha/admin
# * `public_key` key will be labeled "Site key"
# * `private_key` key will be labeled "Secret key"
#
#recaptcha:
#    enabled: false
#    label: "Please enter the reCaptcha text to prove you're a human"
#    public_key: ''
#    private_key: ''
#    error_message: "The CAPTCHA wasn't entered correctly. Please try again."
#    theme: clean

## File Uploads
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SECURITY WARNING ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Handling file uploads is a very common attack vector used to compromise (hack)
# a server.
#
# BoltForms does a few things to help increase slightly the security of handling
# file uploads.
#
# Firstly, the directory that you specify for "base_directory" below should NOT
# be an route accessible to the outside world. We provide a special route should
# you wish to make the files browsable after upload.
#
# Secondly, is the "filename_handling" parameter. If an attacker knows the
# uploaded file name, this can make their job a bit easier. So we provide three
# options, e.g. uploading the file kitten.jpg:
#
# -------------------------------------
# | Setting | Resulting file name     |
# |-----------------------------------|
# | prefix  | kitten.Ze1d352rrI3p.jpg |
# | suffix  | kitten.jpg.Ze1d352rrI3p |
# | keep    | kitten.jpg              |
# -------------------------------------
#
# We recommend "suffix" as this is the most secure, alternatively "prefix" will
# aid in file browsing. However "keep" should always be used with caution!
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SECURITY WARNING ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#uploads:
#    enabled: false                                 # The global on/off switch for upload handling
#    base_directory: /full/path/for/uploaded/files/ # Outside web root and writable by the web server's user
#    filename_handling: suffix                      # Can be either "prefix", "suffix", or "keep"
#    management_controller: false                   # Enable a controller to handle browsing and downloading of uploaded files

## Example 1
#
# Contact Form
contact:
    submission:
        ajax: false                   # Use AJAX for form submission and handling
    notification:
        enabled: true
        debug: false
        #debug_address: name@example.com # Email address used when debug mode is enabled
        #debug_smtp: true
        subject: Your message was submitted
        from_name: Admin                 # Email addresses and names can be either the
        from_email: admin@fyp.co.uk               # name of a field below or valid text.
        replyto_email: p14138628@my365.dmu.ac.uk            #
        replyto_name: name              # NOTE: Email addresses must be valid
        to_name: DMU Foundation Admissions                #
        to_email: james_top986@hotmail.com   #
    feedback:
        success: Message submission successful
        error: There are errors in the form, please fix before trying to resubmit
    fields:
        name:
            type: text
            options:
                required: true
                label: Name
                attr:
                    placeholder: Your name...
                constraints: [ NotBlank, { Length: { 'min': 3, 'max': 128 } } ]
        email:
            type: email
            options:
                required: true
                label: Email address
                attr:
                    placeholder: Your email...
                constraints: [ NotBlank, Email ]
        message:
            type: textarea
            options:
                required: true
                label: Your message
                attr:
                    placeholder: Your message...
                    class: myclass
        needreply:
            type: choice
            options:
                required: false
                label: Do you want us to contact you back?
                choices: { 'Yes': 'yes', 'No': 'no' }
                multiple: false
        submit:
            type: submit
            options:
                label: Submit my message »
                attr:
                    class: button primary

soc:
    notification:
        enabled: true
        subject: PHP Society Enquiry
        from_name: Website
        from_email: php-soc-website@dmu.ac.uk
        to_name: SOC LEader
        to_email: james.top986@gmail.com
    fields:
        comment:
            type: text
            options:
                label: Please Fill in the Form below
                attr:
                    placeholder: Your Name...
                constraints: [ NotBlank, {Length: {'min': 3, 'max': 25}} ]
        email:
            type: email
            options:
                required: true
                label: Email address
                attr:
                    placeholder: Your email...
                constraints: [ NotBlank, Email, {Length: {'max': 35}} ]
        message:
            type: textarea
            options:
                required: true
                label: Your message
                attr:
                    placeholder: Your message...
                    class: myclass
                constraints: [ NotBlank, {Length: {'min': 3, 'max': 400 }} ]
        submit:
            type: submit

fyc_applications:
           # Form field "message" will be saved to the ContentType field "title"
    fields:
        name:
            type: text
            options:
                label: "Your name"
        email:
            type: text
            options:
                label: "Your email"
        mobile:
            type: text
            options:
                label: "Your Mobile Number"
        gcse1:
            type: text
            options:
               required: true
               label: GCSE1    
        gcse1result:
            type: choice
            options:
                label: "GCSE1 Grade"
                choices: { "Grade":"Grade","A*": "A*", "A": "A","B": "B","C": "C","D": "D","E": "E" }
                attr:
                   placeholder: Your email...
                   class: myclass-email
        gcse2:
            type: text
            options:
               required: true
               label: GCSE2    
        gcse2result:
            type: choice
            options:
                label: "GCSE2 Grade"
                choices: { "Grade":"Grade","A*": "A*", "A": "A","B": "B","C": "C","D": "D","E": "E" }
        gcse3:
            type: text
            options:
               required: true
               label: GCSE3    
        gcse3result:
            type: choice
            options:
                label: "GCSE3 Grade"
                choices: { "Grade":"Grade","A*": "A*", "A": "A","B": "B","C": "C","D": "D","E": "E" }  
        gcse4:
            type: text
            options:
               required: true
               label: GCSE4    
        gcse4result:
            type: choice
            options:
                label: "GCSE4 Grade"
                choices: { "Grade":"Grade","A*": "A*", "A": "A","B": "B","C": "C","D": "D","E": "E" } 
        gcse5:
            type: text
            options:
               required: true
               label: GCSE5    
        gcse5result:
            type: choice
            options:
                label: "GCSE5 Grade"
                choices: { "Grade":"Grade","A*": "A*", "A": "A","B": "B","C": "C","D": "D","E": "E" }
        alevel:
            type: text
            options:
               required: false
               label: A level    
        alevelresult:
            type: choice
            options:
                label: "A level Grade"
                choices: { "Grade":"Grade","A*": "A*", "A": "A","B": "B","C": "C","D": "D","E": "E" }
        OtherQual:
                type: text
                options:
                    required: false
                    label: Other Qualifications
        OtherQualResult:
                type: text
                options:
                    required: false
                    label: Other Qualifications Results
        message:
            type: textarea
        status: # Don't publish new record after submitting but leave that to the editor
            type: hidden
            options:
                label: false
                attr:
                    value: draft
        submit:
                type: submit
    database:
           contenttype:
              name: FYCApplications  # ContentType record to create
              field_map:
                  name: 'title'
                  email: 'email'
                  mobile: 'mobile'            
                  gcse1: 'gcse1'
                  gcse1result: 'gcse1result'
                  gcse2: 'gcse2'
                  gcse2result: 'gcse2result'
                  gcse2: 'gcse3'
                  gcse1result: 'gcse3result'
                  gcse4: 'gcse4'
                  gcse4result: 'gcse4result'
                  gcse5: 'gcse5'
                  gcse5result: 'gcse5result'
                  alevel: 'alevel'
                  alevelresult: 'alevelresult'
                  OtherQual: 'OtherQualResult'
                  OtherQualResult: 'OtherQualResult'
                  message: 'sent_message' # Form field "message" will be saved to the ContentType field "sent_message"
       
    feedback:
        success: Form submission sucessful
        error: There are errors in the form, please fix before trying to resubmit
        redirect:
            target: /fyc-blog-entry/application-successful  # A page path, or URL
            query: [ name, email ]     # Optional keys for the GET parameters
           
           
           
## Example 2
#
# Example Showcase Form
#showcase:
#    submission:
#        ajax: false                   # Use AJAX for form submission and handling
#    notification:
#        enabled: true
#        debug: false
#        debug_address: name@example.com # Email address used when debug mode is enabled
#        debug_smtp: true
#        subject: "[TESTING] A showcase form was just submitted"
#        from_name: name               # A field name, specified in the fields: section below
#        replyto_email: email          # A field name, specified in the fields: section below
#        replyto_name: name            # A field name, specified in the fields: section below
#        from_email: email             # A field name, specified in the fields: section below
#        to_name: My Site              # Must be valid text
#        to_email: noreply@example.com # Must be valid email address
#        cc_name: Info Person
#        cc_email: info@example.com
#        bcc_name: Manager Person
#        bcc_email: manager@example.com
#        attach_files: false
#    templates:                      # Over ride the global Twig templates for this form
#        form: extensions/boltforms/form.twig
#        email: extensions/boltforms/email.twig
#        subject: extensions/boltforms/subject.twig
#        files: extensions/boltforms/file_browser.twig
#    feedback:
#        success: Form submission sucessful
#        error: There are errors in the form, please fix before trying to resubmit
#        redirect:
#            target: page/another-page  # A page path, or URL
#            query: [ name, email ]     # Optional keys for the GET parameters
#    database:
#        contenttype:
#           name: mycontenttype  # ContentType record to create
#           field_map:
#               email: ~                # Do not try to save this field to the ContentType
#               message: 'sent_message' # Form field "message" will be saved to the ContentType field "sent_message"
#        table: bolt_secret_table    # Specific database table to write to
#    uploads:
#        subdirectory: showcase_files # The (optional) subdirectory for uploaded files
#    recaptcha: false    # This setting is optional to use the overall default, false is the only valid value to disable for this form only.
#    fields:
#        subject:
#            type: text
#            options:
#                required: true
#                label: Subject of your message
#                attr:
#                    placeholder: Just a quick message...
#                    prefix: '<p>A small HTML prefix</p>'
#                    postfix: '<p>A small HTML postfix</p>'
#                constraints: [ NotBlank, {Length: {'min': 3, 'max': 30}} ]
#        name:
#            type: text
#            options:
#                required: true
#                label: Name
#                attr:
#                    placeholder: Your name...
#                constraints: [ NotBlank, {Length: {'min': 3}} ]
#        email:
#            type: email
#            options:
#                required: true
#                label: Email address
#                attr:
#                    placeholder: Your email...
#                    class: myclass-email
#                constraints: [ NotBlank, Email ]
#        message:
#            type: textarea
#            options:
#                required: true
#                label: Your message
#                attr:
#                    placeholder: Well, the other day I was thinking that maybe you ought to improve your website by adding...
#                    class: myclass-message
#        pet_ownership:
#            type: choice
#            options:
#                required: false
#                label: Do you own a pet?
#                choices: [ Yes, No ]
#                multiple: false
#        cutest_pet:
#            type: choice
#            options:
#                required: false
#                label: Which do you think are cutest?
#                choices: { 'Fluffy Kittens': 'kittens', 'Cute Puppies': 'puppies' }
#        contenttype_choice:
#            type: choice
#            options:
#                required: false
#                label: ContentType selection
#                choices: content
#                params:
#                    contenttype: pages
#                    label: title                    # Field name to get the lable value from
#                    value: slug                     # Field name to get the underlying choice value from
#                    limit: 3                        # Limit on the number of results returned
#                    sort: title                     # Field name to sort on
#                    order: ASC                      # Sorting direction, either "ASC" or "DESC"
#                    where:
#                        and: { 'koala': 'bear' }      # Field name "koala" with the value of "bear"
#                        or: { 'koala': 'dangerous' }  # Field name "koala" with the value of "dangerous"
#        event:
#            type: choice
#            options:
#                required: false
#                label: What event would you like to attend?
#                choices: event # Will be dispatching on \Bolt\Extension\Bolt\BoltForms\Event\BoltFormsEvents::DATA_CHOICE_EVENT
#                multiple: false
#        event_custom:
#            type: choice
#            options:
#                required: false
#                label: What type of animal would you like to bring?
#                choices: event::your.custom.event.name # Will be dispatching on "your.custom.event.name"
#                multiple: false
#        choice_simple:
#            type: choice
#            options:
#                label: A very simple choice
#                choices: { 'Item One': 'item_1', 'Item Two': 'item_2' }
#        choice_traversable_choices_class:
#            type: choice
#            options:
#                required: false
#                label: Traversable choices class with "group_b" passed to the constructor
#                choices: Example\TraversableChoice::group_b
#                choice_label: Example\StaticChoice::choiceLabel
#        choice_static_choices_class:
#            type: choice
#            options:
#                required: false
#                label: Choices from the calls to a static class::function
#                choices: Example\StaticChoice::choices
#                choice_label: Example\StaticChoice::choiceLabel
#        choice_with_attrib:
#            type: choice
#            options:
#                label: HTML attributes added to each choice
#                choices: Example\StaticChoice::choices
#                choice_value: Example\StaticChoice::choiceValue
#                choice_label: Example\StaticChoice::choiceLabel
#                choice_attr: Example\StaticChoice::choiceAttr
#        group_simple:
#            type: choice
#            options:
#                label: Grouping Simple
#                choices:
#                    'Group Aye': { 'Item One': 'item_1', 'Item Two': 'item_2', }
#                    'Group Bee': { 'Item Eleven': 'item_11', 'Item Twelve': 'item_12' }
#        choice_group_callouts:
#            type: choice
#            options:
#                required: false
#                label: Grouping callouts
#                choices: Example\StaticChoice::choices
#                choice_label: Example\StaticChoice::choiceLabel
#                group_by: Example\StaticChoice::groupBy
#        choice_group_callouts_preferred_choices:
#            type: choice
#            options:
#                required: false
#                label: Grouping callouts with preferred choices
#                choices: Example\StaticChoice::choices
#                choice_label: Example\StaticChoice::choiceLabel
#                preferred_choices: Example\StaticChoice::preferredChoices
#                multiple: false
#        upload:
#            type: file
#            options:
#                required: false
#                label: Picture of your pet that you want us to add to our site
#        submit:
#            type: submit
#            options:
#                label: Submit my message »
#                attr:
#                    class: button primary
